### ISSUE TITLE
Very interesting but where is the SASS?

### ISSUE THREAD

**Issue by jcklpe** [Elbullazul/B00merang-Flat#1]
It says sass based but I don't see any sass or scss files?

**Comment by Elbullazul** [comment]
sorry for late reply. I'm trying to retro-engineer the current GTK CSS to SCSS by adapting syntax and color names. It's going great, just need to swap out the color variables for HEX values and I'll commit to a new branch

**Comment by Elbullazul** [comment]
https://github.com/B00merang-Project/Azurra_framework/tree/master/B00merang/flat
